In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("Titanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
df.drop(["PassengerId","Name","Ticket"], axis=1, inplace=True)

In [5]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [6]:
DROP_COLUMNS = ["PassengerId","Name","Ticket"]

In [7]:
def drop_cols(df: pd.DataFrame, cols: list[str])-> pd.DataFrame:
    """
    Drop specific cols from df
    """

    return df.drop(columns=cols)

In [8]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

<h1>Check Data Types</h1>

In [9]:
df.dtypes

Survived      int64
Pclass        int64
Sex             str
Age         float64
SibSp         int64
Parch         int64
Fare        float64
Cabin           str
Embarked        str
dtype: object

In [10]:
dtypes = df.dtypes
n_uniq = df.nunique()
pd.DataFrame({"Dtypes : ":dtypes, "Num_Uniqu": n_uniq }).T

          Survived Pclass  Sex      Age  SibSp  Parch     Fare Cabin Embarked
Dtypes :     int64  int64  str  float64  int64  int64  float64   str      str
Num_Uniqu        2      3    2       88      7      7      248   147        3

In [11]:
from ps import get_check_dtype
get_check_dtype(df)

          Survived Pclass  Sex      Age  SibSp  Parch     Fare Cabin Embarked
Dtypes       int64  int64  str  float64  int64  int64  float64   str      str
Num_Uniqu        2      3    2       88      7      7      248   147        3

In [20]:
df.shape[0]

891

In [23]:
null = df.isnull().sum()
ratio = null / df.shape[0]
pd.DataFrame({"nulls_sum": null, "ratio ": ratio}).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
nulls_sum,0.0,0.0,0.0,177.000000,0.0,0.0,0.0,687.000000,2.000000
ratio,0.0,0.0,0.0,0.198653,0.0,0.0,0.0,0.771044,0.002245

In [38]:
cols = ['Survived', 'SibSp', 'Sex','Parch', 'Embarked' ]
df[cols] = df[cols].astype('category')
pd.DataFrame(df.dtypes).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,category,category,category,float64,category,category,float64,category

In [39]:
df = df.dropna(subset=['Embarked'])

In [43]:
mean = df['Age'].mean()
print(mean)
print("=" * 40)
median_1 = df['Age'].median()
print(median_1)
df['Age'].fillna(median_1, inplace= True)
df.head()

29.64209269662921
========================================
28.0

C:\Users\Fahd\AppData\Local\Temp\ipykernel_9368\91719063.py:6: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Age'].fillna(median_1, inplace= True)

  Survived Pclass     Sex   Age SibSp Parch     Fare Embarked
0        0      3    male  22.0     1     0   7.2500        S
1        1      1  female  38.0     1     0  71.2833        C
2        1      3  female  26.0     0     0   7.9250        S
3        1      1  female  35.0     1     0  53.1000        S
4        0      3    male  35.0     0     0   8.0500        S

In [31]:
null = df.isnull().sum()
ratio = null / df.shape[0]
pd.DataFrame({"nulls_sum": null, "ratio ": ratio}).T

           Survived  Pclass  Sex       Age  SibSp  Parch  Fare  Embarked
nulls_sum       0.0     0.0  0.0  177.0000    0.0    0.0   0.0       0.0
ratio           0.0     0.0  0.0    0.1991    0.0    0.0   0.0       0.0

In [32]:
df.describe()

           Pclass         Age        Fare
count  889.000000  712.000000  889.000000
mean     2.311586   29.642093   32.096681
std      0.834700   14.492933   49.697504
min      1.000000    0.420000    0.000000
25%      2.000000   20.000000    7.895800
50%      3.000000   28.000000   14.454200
75%      3.000000   38.000000   31.000000
max      3.000000   80.000000  512.329200

In [33]:
num_cols = df.select_dtypes("number").columns
num_cols

Index(['Pclass', 'Age', 'Fare'], dtype='str')